### ISSUE TITLE
Move to Markdown

### ISSUE THREAD

**Issue by vestimir** [WordPress/Security-White-Paper#1]
First of all, thanks for this wonderful document. 

I have a proposal - let's move this to markdown - so it's easier to edit and also Pandoc can be used to create automatically versions in different formats (PDF, HTML, etc. ). What do you think, I can send a PR about this.

**Comment by sararosso** [comment]
I appreciate the suggestion but HTML is much more widespread and will enable a larger part of the community to manipulate, update, and use the document. 

You're welcome to create your own version using Markdown, but we won't be moving the master version to that. Thanks for your feedback! :)

**Comment by vestimir** [comment]
:+1:
