### ISSUE TITLE
Update OWASP Top 10 after 2017 release

### ISSUE THREAD

**Issue by iandunn** [WordPress/Security-White-Paper#49]
OWASP is [working on an update to the 2013 Top 10](https://www.owasp.org/index.php/Category:OWASP_Top_Ten_Project#2017_Update_Data_Call), with a tentative release date some time in 2017. There's nothing for us to do right now, but we should keep an eye out for the release, and update the white paper to reflect any changes in the final version.

**Comment by pkevan** [comment]
This issue can be closed as there is another update - tracking in #76
