### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by angelfplaza** [WordPress/Security-White-Paper#65]
"Phase 3: Beta. Betas are released, and beta-testers are asked to start reporting bugs. **No more commits for new enhancements or feature requests are carried out from this phase on.** Third-party plugin and theme authors are encouraged to test their code against the upcoming changes."
I think something is missing on the selected text.

Edit: I am trying to translate, so maybe the phrase is correct and I do not understand it well. 
Thanks!

**Comment by Otto42** [comment]
The phrase is correct, but I agree that it might be unclear. What it means is that after WordPress enters beta, no new changes (commits) are accepted for new features or new enhancements. The beta phase is solely for testing and finding bugs from the new features already added, before the final release. This is a fairly standard definition of "beta" for software projects.

**Comment by pkevan** [comment]
Given there doesn't appear to be anything to change here, lets close.
