### ISSUE TITLE
Move complete French translations

### ISSUE THREAD

**Issue by fxbenard** [WordPress/Security-White-Paper#70]
French translations is completed, it should be moved on folder up

**Comment by desrosj** [comment]
Hi @fxbenard, sorry that this took so long to get to. Are you able to triple check that French translations still match the current state of the document?

**Comment by fxbenard** [comment]
Project seems not to have changed since, so the translation is still up to date

**Comment by pkevan** [comment]
Fixed in https://github.com/WordPress/Security-White-Paper/commit/60416068135d4aeba1d00d838db492c824a714f0
