### ISSUE TITLE
Review Indonesian Working Translation

### ISSUE THREAD

**Issue by sararosso** [WordPress/Security-White-Paper#9]
I'd like a few more members of the community to give the Indonesian working translation a read so we can make it an official translation. 

https://github.com/WordPress/Security-White-Paper/blob/master/Working%20Translations/id/BukuPutihKeamananWordPress.html

Please leave your comments on this thread, and/or make a pull request against the file.

**Comment by sararosso** [comment]
@ekajogja could you get a few members of your community to weigh in? Thanks :)

**Comment by ekajogja** [comment]
Not sure if can I get people here. I believe there's an Indonesian staff working in Automattic, though.

**Comment by hafizrahman** [comment]
LGTM :)

**Comment by sararosso** [comment]
Thanks @hafizrahman!

**Comment by sararosso** [comment]
@ekajogja I'm going to close this issue. Can you move the translation into /id in the top directory and submit a pull request?
